version: '3.9'

x-logging:
  &highlight-logging 
    driver: fluentd 
    options: 
	    fluentd-address: "otel.highlight.io:24224" 
	    fluentd-async: "true" 
	    fluentd-sub-second-precision: "true" 
	    tag: "highlight.project_id=ng2oxzrd"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/guanyuchi.com/images:/app/images
    depends_on:
      - db
    logging: *highlight-logging

  caddy:
    image: caddy 
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging: *highlight-logging

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ~/data/guanyuchi.com/psql:/var/lib/postgresql/data/pgdata
    logging: *highlight-logging
    