version: '3.9'

services:
  db:
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESISN: dracula
    ports:
      - 3333:8080

  tailwind:
    build:
      context: ./tailwind
      dockerfile: dockerfile
    tty: true
    restart: always
    volumes:
      - ./tailwind:/src
      - ./assets:/dst
      - ./templates:/templates