steps:
- name: Set up Go 1.x
  uses: actions/setup-go@v4
  with:
    go-version: ^1.20
  id: go

- name: Check out code into the Go module directory
  uses: actions/checkout@v3

- name: golang-migraterun:
  run:
    go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest
    which migrate

- name: Run migrates
  run: make migrateup

- name: Test
  run: make test